### ISSUE TITLE
Any way to configure installed windows components (i.e. IIS)?

### ISSUE THREAD

**Issue by simonkirkham** [gusztavvargadr/workstations#64]
Is there an easy way to configure IIS to be enabled/installed in the windows features as part of the provisioning? The w10e-vs17c image doesn't appear to have it.

**Comment by gusztavvargadr** [comment]
@simonkirkham yes, you can take a look at the samples in the `Core` section: https://github.com/gusztavvargadr/workstations#core.

For IIS you can add something similar to your machine's YAML configuration:

```yml
playground:
  # omitted
  chef:
    json:
      # omitted
      gusztavvargadr_workstations_core:
        requirements:
          features:
            IIS:
```

This is supposed to install all the Windows Features matching `IIS`.
